// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: my.proto

#pragma warning disable 1591, 0612, 3021
namespace protob
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Hands : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Hands()
        {
            hands = new global::System.Collections.Generic.List<Hand>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<Hand> hands { get; private set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Hand : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Hand()
        {
            fingers = new global::System.Collections.Generic.List<Point>();
            wrist = new global::System.Collections.Generic.List<Point>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<Point> fingers { get; private set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<Point> wrist { get; private set; }

        [global::ProtoBuf.ProtoMember(3)]
        public Point palmCenter { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Point : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Point()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public PointXYZ pointXYZ { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public PointIJ pointIJ { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PointXYZ : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public PointXYZ()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public float x { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public float y { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public float z { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PointIJ : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public PointIJ()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public int i { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int j { get; set; }

    }

}

#pragma warning restore 1591, 0612, 3021
