get_filename_component(CMAKE_FILE_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
SET(DBoW2_LIBRARIES "${CMAKE_FILE_DIR}/../../DBoW2.lib")
SET(DBoW2_LIBS ${DBoW2_LIBRARIES})
SET(DBoW2_INCLUDE_DIRS "${CMAKE_FILE_DIR}/../../../include/DBoW2")
